config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :moods
    resources :notes
    resources :organizations
    resources :teams
    resources :users

    root to: "moods#index"
  end

  constraints Clearance::Constraints::SignedIn.new do
    root to: 'welcome_auth#index', as: :signed_in_root

    get 'profile/index'

    get 'welcome_auth/index'
    post 'welcome_auth/create'

    resources :moods, only: [:create, :new, :index]

    resource :users, only: [:update], as: :user
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: 'welcome#index'

    resources :users, controller: "users", only: [:create] do
      resource :password,
        controller: "clearance/passwords",
        only: [:create, :edit, :update]
    end
  end

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"

  get 'welcome/index'

end

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key} alert-dismissible fade in"}
    %button.close{:type => 'button', 'data-dismiss' => 'alert', 'aria-label' => 'Close'}
      %span{'aria-hidden' => true}
        = '&times;'.html_safe
    = value

app/views/layouts/application.html.haml
!!!
%html{ lang: 'en' }
  %head
    %title Koni Koni
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tag
  %body
    .container-fluid.main
      %nav.navbar.navbar-light.bg-faded.navbar-fixed-top
        = link_to 'Koni', root_path, class: 'navbar-brand'
        - if signed_in?
          %ul.nav.navbar-nav
            %li.nav-item
              = link_to 'History', moods_path, class: ['nav-link', ('active' if current_page?(controller: 'moods', action: 'index'))]
        %ul.nav.navbar-nav.pull-xs-right
          - if signed_in?
            %li.nav-item
              = link_to current_user.name, profile_index_path, class: ['nav-link', ('active' if current_page?(controller: 'profile', action: 'index'))]
            %li.nav-item
              = link_to t('.sign_out'), sign_out_path, method: :delete, class: 'nav-link'
          - else
            %li.nav-item
              = link_to t('.sign_in'), sign_in_path, class: 'nav-link'
      #flash.container
        = render 'layouts/flash'
      = yield